name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone submodules
      run: git submodule init && git submodule update --init --recursive
    - name: Prepare environment
      run: sudo make setup && sudo apt install zip
    - name: Compile system
      run: make all
    - name: Archive target
      run: mkdir tbu && cp targets_debug tbu/debug -r && cp targets_executeable/tunnel.* tbu/ && zip tunnel.zip tbu -r9v
    - name: Upload target
      uses: actions/upload-artifact@v3.1.0
      with:
        name: tunnel.zip
        path: ./tunnel.zip
